name: Build and Publish NuGet Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Create nupkgs directory
        run: mkdir -p nupkgs

      - name: Pack the project
        run: dotnet pack --configuration Release --output nupkgs

      - name: Publish NuGet Package
        run: dotnet nuget push nupkgs/*.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/ --api-key ${{ secrets.GITHUB_TOKEN }}
